import { Component } from '@angular/core';

@Component({
  selector: 'app-gallery',
  standalone: false,
  //imports: [],
  templateUrl: './gallery.component.html',
  styleUrl: './gallery.component.scss'
})
export class GalleryComponent {
  // images: GalleryItem[];

  // constructor() {
  //   this.images = [
  //     new ImageItem({ src: 'assets/images/gallery/deer1.JPG', thumb: 'assets/images/gallery/deer1.JPG' }),
  //     new ImageItem({ src: 'assets/images/gallery/roeDeer.jpg', thumb: 'assets/images/gallery/roeDeer.jpg' }),
  //   ];
  // }

  images = [
    { src: 'assets/images/gallery/017-P1020488.JPG', thumb: 'assets/images/gallery/017-P1020488.JPG' },
    { src: 'assets/images/gallery/156-P1020334.JPG', thumb: 'assets/images/gallery/156-P1020334.JPG' },
    { src: 'assets/images/gallery/175-P1000106.JPG', thumb: 'assets/images/gallery/175-P1000106.JPG' },
    { src: 'assets/images/gallery/176-P1000108.JPG', thumb: 'assets/images/gallery/176-P1000108.JPG' },
    { src: 'assets/images/gallery/20140522_124550.jpg', thumb: 'assets/images/gallery/20140522_124550.jpg' },
    { src: 'assets/images/gallery/8234650092_78a44d6cf1_n.jpg', thumb: 'assets/images/gallery/8234650092_78a44d6cf1_n.jpg' },
    { src: 'assets/images/gallery/Board walk Brocken Spectre.jpg', thumb: 'assets/images/gallery/Board walk Brocken Spectre.jpg' },
    { src: 'assets/images/gallery/Board Walk.jpg', thumb: 'assets/images/gallery/Board Walk.jpg' },
    { src: 'assets/images/gallery/Branch (2).jpg', thumb: 'assets/images/gallery/Branch (2).jpg' },
    { src: 'assets/images/gallery/Branch.jpg', thumb: 'assets/images/gallery/Branch.jpg' },
    { src: 'assets/images/gallery/burrowing bumblebee (1).jpg', thumb: 'assets/images/gallery/burrowing bumblebee (1).jpg' },
    { src: 'assets/images/gallery/Clearing.jpg', thumb: 'assets/images/gallery/Clearing.jpg' },
    { src: 'assets/images/gallery/damselfly (1).jpg', thumb: 'assets/images/gallery/damselfly (1).jpg' },
    { src: 'assets/images/gallery/deer1.JPG', thumb: 'assets/images/gallery/deer1.JPG' },
    { src: 'assets/images/gallery/Dougal & Calum_5x7.jpg', thumb: 'assets/images/gallery/Dougal & Calum_5x7.jpg' },
    { src: 'assets/images/gallery/drinker moth caterpillar (1).jpg', thumb: 'assets/images/gallery/drinker moth caterpillar (1).jpg' },
    { src: 'assets/images/gallery/DSC_0828.jpg', thumb: 'assets/images/gallery/DSC_0828.jpg' },
    { src: 'assets/images/gallery/DSC_1224.jpg', thumb: 'assets/images/gallery/DSC_1224.jpg' },
    { src: 'assets/images/gallery/DSC_1230.jpg', thumb: 'assets/images/gallery/DSC_1230.jpg' },
    { src: 'assets/images/gallery/DSC_1464.jpg', thumb: 'assets/images/gallery/DSC_1464.jpg' },
    { src: 'assets/images/gallery/DSC_1479.jpg', thumb: 'assets/images/gallery/DSC_1479.jpg' },
    { src: 'assets/images/gallery/DSC_1489.jpg', thumb: 'assets/images/gallery/DSC_1489.jpg' },
    { src: 'assets/images/gallery/DSC_1517.jpg', thumb: 'assets/images/gallery/DSC_1517.jpg' },
    { src: 'assets/images/gallery/DSC_1776.jpg', thumb: 'assets/images/gallery/DSC_1776.jpg' },
    { src: 'assets/images/gallery/DSC_2049.jpg', thumb: 'assets/images/gallery/DSC_2049.jpg' },
    { src: 'assets/images/gallery/DSC_2228.JPG', thumb: 'assets/images/gallery/DSC_2228.JPG' },
    { src: 'assets/images/gallery/DSC_2230.JPG', thumb: 'assets/images/gallery/DSC_2230.JPG' },
    { src: 'assets/images/gallery/DSC_2234.JPG', thumb: 'assets/images/gallery/DSC_2234.JPG' },
    { src: 'assets/images/gallery/DSC_2241.jpg', thumb: 'assets/images/gallery/DSC_2241.jpg' },
    { src: 'assets/images/gallery/DSC_2242.JPG', thumb: 'assets/images/gallery/DSC_2242.JPG' },
    { src: 'assets/images/gallery/DSC_2259.JPG', thumb: 'assets/images/gallery/DSC_2259.JPG' },
    { src: 'assets/images/gallery/DSC_2270.JPG', thumb: 'assets/images/gallery/DSC_2270.JPG' },
    { src: 'assets/images/gallery/DSC_3378.jpg', thumb: 'assets/images/gallery/DSC_3378.jpg' },
    { src: 'assets/images/gallery/DSC_3640.jpg', thumb: 'assets/images/gallery/DSC_3640.jpg' },
    { src: 'assets/images/gallery/DSC_3654.jpg', thumb: 'assets/images/gallery/DSC_3654.jpg' },
    { src: 'assets/images/gallery/DSC_4451.JPG', thumb: 'assets/images/gallery/DSC_4451.JPG' },
    { src: 'assets/images/gallery/DSC_6444.JPG', thumb: 'assets/images/gallery/DSC_6444.JPG' },
    { src: 'assets/images/gallery/DSC_6454.JPG', thumb: 'assets/images/gallery/DSC_6454.JPG' },
    { src: 'assets/images/gallery/DSC_6989.jpg', thumb: 'assets/images/gallery/DSC_6989.jpg' },
    { src: 'assets/images/gallery/DSC_6998.jpg', thumb: 'assets/images/gallery/DSC_6998.jpg' },
    { src: 'assets/images/gallery/DSC_7002.jpg', thumb: 'assets/images/gallery/DSC_7002.jpg' },
    { src: 'assets/images/gallery/DSC_7003.jpg', thumb: 'assets/images/gallery/DSC_7003.jpg' },
    { src: 'assets/images/gallery/DSC_7027.jpg', thumb: 'assets/images/gallery/DSC_7027.jpg' },
    { src: 'assets/images/gallery/DSC_7450.jpg', thumb: 'assets/images/gallery/DSC_7450.jpg' },
    { src: 'assets/images/gallery/DSC_7454.jpg', thumb: 'assets/images/gallery/DSC_7454.jpg' },
    { src: 'assets/images/gallery/DSC_7458.jpg', thumb: 'assets/images/gallery/DSC_7458.jpg' },
    { src: 'assets/images/gallery/DSC_7461.jpg', thumb: 'assets/images/gallery/DSC_7461.jpg' },
    { src: 'assets/images/gallery/DSC_7464.jpg', thumb: 'assets/images/gallery/DSC_7464.jpg' },
    { src: 'assets/images/gallery/DSC_7468.jpg', thumb: 'assets/images/gallery/DSC_7468.jpg' },
    { src: 'assets/images/gallery/DSC_7472.jpg', thumb: 'assets/images/gallery/DSC_7472.jpg' },
    { src: 'assets/images/gallery/DSC_7477.jpg', thumb: 'assets/images/gallery/DSC_7477.jpg' },
    { src: 'assets/images/gallery/DSC_7479.jpg', thumb: 'assets/images/gallery/DSC_7479.jpg' },
    { src: 'assets/images/gallery/DSC_7482.jpg', thumb: 'assets/images/gallery/DSC_7482.jpg' },
    { src: 'assets/images/gallery/DSC_7723.jpg', thumb: 'assets/images/gallery/DSC_7723.jpg' },
    { src: 'assets/images/gallery/DSC_8353.JPG', thumb: 'assets/images/gallery/DSC_8353.JPG' },
    { src: 'assets/images/gallery/DSC_8770.jpg', thumb: 'assets/images/gallery/DSC_8770.jpg' },
    { src: 'assets/images/gallery/DSC_8894.JPG', thumb: 'assets/images/gallery/DSC_8894.JPG' },
    { src: 'assets/images/gallery/DSC_8928.JPG', thumb: 'assets/images/gallery/DSC_8928.JPG' },
    { src: 'assets/images/gallery/DSC_8931.JPG', thumb: 'assets/images/gallery/DSC_8931.JPG' },
    { src: 'assets/images/gallery/DSC_8942.JPG', thumb: 'assets/images/gallery/DSC_8942.JPG' },
    { src: 'assets/images/gallery/Edit 1 (Jamie).JPG', thumb: 'assets/images/gallery/Edit 1 (Jamie).JPG' },
    { src: 'assets/images/gallery/Edit 18 (Kyle).JPG', thumb: 'assets/images/gallery/Edit 18 (Kyle).JPG' },
    { src: 'assets/images/gallery/Edit 2 (Jamie).JPG', thumb: 'assets/images/gallery/Edit 2 (Jamie).JPG' },
    { src: 'assets/images/gallery/Edit 27.JPG', thumb: 'assets/images/gallery/Edit 27.JPG' },
    { src: 'assets/images/gallery/Entwined Trees.jpg', thumb: 'assets/images/gallery/Entwined Trees.jpg' },
    { src: 'assets/images/gallery/frogs.jpg', thumb: 'assets/images/gallery/frogs.jpg' },
    { src: 'assets/images/gallery/green hairstreak butterfly 1 (1).jpg', thumb: 'assets/images/gallery/green hairstreak butterfly 1 (1).jpg' },
    { src: 'assets/images/gallery/green hairstreak butterfly 2 (1).jpg', thumb: 'assets/images/gallery/green hairstreak butterfly 2 (1).jpg' },
    { src: 'assets/images/gallery/green hairstreak butterfly 3 (1).jpg', thumb: 'assets/images/gallery/green hairstreak butterfly 3 (1).jpg' },
    { src: 'assets/images/gallery/green hairstreak butterfly closeup (1).jpg', thumb: 'assets/images/gallery/green hairstreak butterfly closeup (1).jpg' },
    { src: 'assets/images/gallery/image (1).jpg', thumb: 'assets/images/gallery/image (1).jpg' },
    { src: 'assets/images/gallery/image (2).jpg', thumb: 'assets/images/gallery/image (2).jpg' },
    { src: 'assets/images/gallery/image (4).jpg', thumb: 'assets/images/gallery/image (4).jpg' },
    { src: 'assets/images/gallery/image (5).jpg', thumb: 'assets/images/gallery/image (5).jpg' },
    { src: 'assets/images/gallery/image (6).jpg', thumb: 'assets/images/gallery/image (6).jpg' },
    { src: 'assets/images/gallery/image (7).jpg', thumb: 'assets/images/gallery/image (7).jpg' },
    { src: 'assets/images/gallery/image(1).jpg', thumb: 'assets/images/gallery/image(1).jpg' },
    { src: 'assets/images/gallery/image.jpg', thumb: 'assets/images/gallery/image.jpg' },
    { src: 'assets/images/gallery/Lenzie Moss panorama Ken Thomson.jpg', thumb: 'assets/images/gallery/Lenzie Moss panorama Ken Thomson.jpg' },
    { src: 'assets/images/gallery/Lenzie Moss tree.jpg', thumb: 'assets/images/gallery/Lenzie Moss tree.jpg' },
    { src: 'assets/images/gallery/Long Tail Tit_2.jpg', thumb: 'assets/images/gallery/Long Tail Tit_2.jpg' },
    { src: 'assets/images/gallery/photo (1).JPG', thumb: 'assets/images/gallery/photo (1).JPG' },
    { src: 'assets/images/gallery/photo (2)(1).JPG', thumb: 'assets/images/gallery/photo (2)(1).JPG' },
    { src: 'assets/images/gallery/photo (2).JPG', thumb: 'assets/images/gallery/photo (2).JPG' },
    { src: 'assets/images/gallery/photo (3).JPG', thumb: 'assets/images/gallery/photo (3).JPG' },
    { src: 'assets/images/gallery/photo (4).JPG', thumb: 'assets/images/gallery/photo (4).JPG' },
    { src: 'assets/images/gallery/photo (5).JPG', thumb: 'assets/images/gallery/photo (5).JPG' },
    { src: 'assets/images/gallery/photo (6).JPG', thumb: 'assets/images/gallery/photo (6).JPG' },
    { src: 'assets/images/gallery/photo 1(1).JPG', thumb: 'assets/images/gallery/photo 1(1).JPG' },
    { src: 'assets/images/gallery/photo 1.JPG', thumb: 'assets/images/gallery/photo 1.JPG' },
    { src: 'assets/images/gallery/photo 2.JPG', thumb: 'assets/images/gallery/photo 2.JPG' },
    { src: 'assets/images/gallery/photo 3.JPG', thumb: 'assets/images/gallery/photo 3.JPG' },
    { src: 'assets/images/gallery/photo(1).JPG', thumb: 'assets/images/gallery/photo(1).JPG' },
    { src: 'assets/images/gallery/photo.JPG', thumb: 'assets/images/gallery/photo.JPG' },
    { src: 'assets/images/gallery/photo5.JPG', thumb: 'assets/images/gallery/photo5.JPG' },
    { src: 'assets/images/gallery/Pruned to Perfection.JPG', thumb: 'assets/images/gallery/Pruned to Perfection.JPG' },
    { src: 'assets/images/gallery/Reflections on a windy day.JPG', thumb: 'assets/images/gallery/Reflections on a windy day.JPG' },
    { src: 'assets/images/gallery/roeDeer.jpg', thumb: 'assets/images/gallery/roeDeer.jpg' },
    { src: 'assets/images/gallery/SAM_7309.JPG', thumb: 'assets/images/gallery/SAM_7309.JPG' },
    { src: 'assets/images/gallery/SAM_7313.JPG', thumb: 'assets/images/gallery/SAM_7313.JPG' },
    { src: 'assets/images/gallery/SAM_7318.JPG', thumb: 'assets/images/gallery/SAM_7318.JPG' },
    { src: 'assets/images/gallery/SAM_7328.JPG', thumb: 'assets/images/gallery/SAM_7328.JPG' },
    { src: 'assets/images/gallery/SAM_7330.JPG', thumb: 'assets/images/gallery/SAM_7330.JPG' },
    { src: 'assets/images/gallery/SAM_7996.JPG', thumb: 'assets/images/gallery/SAM_7996.JPG' },
    { src: 'assets/images/gallery/Tree and sky trail.jpg', thumb: 'assets/images/gallery/Tree and sky trail.jpg' },
    { src: 'assets/images/gallery/Whitelaw1.jpg', thumb: 'assets/images/gallery/Whitelaw1.jpg' },
    { src: 'assets/images/gallery/Whitelaw2.jpg', thumb: 'assets/images/gallery/Whitelaw2.jpg' },
    { src: 'assets/images/gallery/Whitelaw3.jpg', thumb: 'assets/images/gallery/Whitelaw3.jpg' },
    { src: 'assets/images/gallery/Winter Tree.JPG', thumb: 'assets/images/gallery/Winter Tree.JPG' },
    { src: 'assets/images/gallery/Winter Wonderland (1).JPG', thumb: 'assets/images/gallery/Winter Wonderland (1).JPG' },
    { src: 'assets/images/gallery/WP_20140613_005.jpg', thumb: 'assets/images/gallery/WP_20140613_005.jpg' },
    { src: 'assets/images/gallery/wren_4.jpg', thumb: 'assets/images/gallery/wren_4.jpg' },
    //drone images
    // { src: 'assets/images/gallery/Boardwalk.JPG', thumb: 'assets/images/gallery/Boardwalk.JPG' },
    // { src: 'assets/images/gallery/dams1.JPG', thumb: 'assets/images/gallery/dams1.JPG' },
    // { src: 'assets/images/gallery/DJI_0161.JPG', thumb: 'assets/images/gallery/DJI_0161.JPG' },
    // { src: 'assets/images/gallery/DJI_0162.JPG', thumb: 'assets/images/gallery/DJI_0162.JPG' },
    // { src: 'assets/images/gallery/DJI_0163.JPG', thumb: 'assets/images/gallery/DJI_0163.JPG' },
    // { src: 'assets/images/gallery/DJI_0164.JPG', thumb: 'assets/images/gallery/DJI_0164.JPG' },
    // { src: 'assets/images/gallery/DJI_0165.JPG', thumb: 'assets/images/gallery/DJI_0165.JPG' },
    // { src: 'assets/images/gallery/DJI_0166.JPG', thumb: 'assets/images/gallery/DJI_0166.JPG' },
    // { src: 'assets/images/gallery/DJI_0167.JPG', thumb: 'assets/images/gallery/DJI_0167.JPG' },
    // { src: 'assets/images/gallery/DJI_0168.JPG', thumb: 'assets/images/gallery/DJI_0168.JPG' },
    // { src: 'assets/images/gallery/DJI_0170.JPG', thumb: 'assets/images/gallery/DJI_0170.JPG' },
    // { src: 'assets/images/gallery/DJI_0171.JPG', thumb: 'assets/images/gallery/DJI_0171.JPG' },
    // { src: 'assets/images/gallery/DJI_0173.JPG', thumb: 'assets/images/gallery/DJI_0173.JPG' },
    // { src: 'assets/images/gallery/DJI_0174.JPG', thumb: 'assets/images/gallery/DJI_0174.JPG' },
    // { src: 'assets/images/gallery/DJI_0176.JPG', thumb: 'assets/images/gallery/DJI_0176.JPG' },
    // { src: 'assets/images/gallery/DJI_0177.JPG', thumb: 'assets/images/gallery/DJI_0177.JPG' },
    // { src: 'assets/images/gallery/DJI_0179.JPG', thumb: 'assets/images/gallery/DJI_0179.JPG' },
    // { src: 'assets/images/gallery/DJI_0183.JPG', thumb: 'assets/images/gallery/DJI_0183.JPG' },
    // { src: 'assets/images/gallery/DJI_0185.JPG', thumb: 'assets/images/gallery/DJI_0185.JPG' },
    // { src: 'assets/images/gallery/DJI_0186.JPG', thumb: 'assets/images/gallery/DJI_0186.JPG' },
    // { src: 'assets/images/gallery/DJI_0188.JPG', thumb: 'assets/images/gallery/DJI_0188.JPG' },
    // { src: 'assets/images/gallery/DJI_0189.JPG', thumb: 'assets/images/gallery/DJI_0189.JPG' },
    // { src: 'assets/images/gallery/DJI_0190.JPG', thumb: 'assets/images/gallery/DJI_0190.JPG' },
    // { src: 'assets/images/gallery/DJI_0191.JPG', thumb: 'assets/images/gallery/DJI_0191.JPG' },
    // { src: 'assets/images/gallery/DJI_0192.JPG', thumb: 'assets/images/gallery/DJI_0192.JPG' },
    // { src: 'assets/images/gallery/DJI_0193.JPG', thumb: 'assets/images/gallery/DJI_0193.JPG' },
    // { src: 'assets/images/gallery/DJI_0195.JPG', thumb: 'assets/images/gallery/DJI_0195.JPG' },
    // { src: 'assets/images/gallery/DJI_0197.JPG', thumb: 'assets/images/gallery/DJI_0197.JPG' },
    // { src: 'assets/images/gallery/DJI_0198.JPG', thumb: 'assets/images/gallery/DJI_0198.JPG' },
    // { src: 'assets/images/gallery/DJI_0199.JPG', thumb: 'assets/images/gallery/DJI_0199.JPG' },
    // { src: 'assets/images/gallery/DJI_0200.JPG', thumb: 'assets/images/gallery/DJI_0200.JPG' },
    // { src: 'assets/images/gallery/DJI_0201.JPG', thumb: 'assets/images/gallery/DJI_0201.JPG' },
    // { src: 'assets/images/gallery/DJI_0202.JPG', thumb: 'assets/images/gallery/DJI_0202.JPG' },
    // { src: 'assets/images/gallery/DJI_0203.JPG', thumb: 'assets/images/gallery/DJI_0203.JPG' },
    // { src: 'assets/images/gallery/DJI_0204.JPG', thumb: 'assets/images/gallery/DJI_0204.JPG' },
    // { src: 'assets/images/gallery/DJI_0205.JPG', thumb: 'assets/images/gallery/DJI_0205.JPG' },
    // { src: 'assets/images/gallery/DJI_0206.JPG', thumb: 'assets/images/gallery/DJI_0206.JPG' },
    // { src: 'assets/images/gallery/east.JPG', thumb: 'assets/images/gallery/east.JPG' },
    // { src: 'assets/images/gallery/eastmoss.JPG', thumb: 'assets/images/gallery/eastmoss.JPG' },
    // { src: 'assets/images/gallery/north.JPG', thumb: 'assets/images/gallery/north.JPG' },
    // { src: 'assets/images/gallery/schools.JPG', thumb: 'assets/images/gallery/schools.JPG' },
    // { src: 'assets/images/gallery/South Lenzie Moss.JPG', thumb: 'assets/images/gallery/South Lenzie Moss.JPG' },
    // { src: 'assets/images/gallery/south.JPG', thumb: 'assets/images/gallery/south.JPG' },
    // { src: 'assets/images/gallery/west.JPG', thumb: 'assets/images/gallery/west.JPG' }
  ];

}
