name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  workflow_dispatch:

env:
  docker_image_tag: ryantodd/hashedselkie_moss:0.0.${{ github.run_number }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        path: repo

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context: repo
       push: true
       tags: ${{ env.docker_image_tag }}
